---
driver:
  name: vagrant

transport:
  password: vagrant
  username: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8
  client_rb:
    ssl_verify_mode: :verify_none
    log_level: :debug

platforms:
  - name: win-2012r2-standard-amd64-nocm
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      box_url: https://atlas.hashicorp.com/opentable/boxes/win-2012r2-standard-amd64-nocm/versions/1.0.0/providers/virtualbox.box
      guest: windows
      network:
      - ["forwarded_port", {guest: 3389, host: 3389}]
      - ["private_network", {type: "dhcp"}]
      customize:
        memory: 4096
        natdnshostresolver1: "on"
        natdnsproxy1: "on"

suites:
  - name: dnx_1_0_0_rc1_update1_x86
    run_list:
      - recipe[dotnetframework::dnx-1-0-0-rc1-update1-x86]
    attributes: